apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-back
  namespace: app-unir
  labels:
    app: todo-app-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app-back
  template:
    metadata:
      labels:
        app: todo-app-back
    spec:
      containers:
      - name: todo-app-back
        image: jm9704/todo-app-back:v1 # Imagen de Docker Hub
        ports:
        - containerPort: 8080 # Puerto en el que tu app escucha
        resources:
          limits:
            memory: 200Mi
            cpu: "1"
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: MONGODB_PASS
          valueFrom: 
            secretKeyRef:
              name: todo-app-back-secret
              key: MONGODB_PASS
        - name: MONGODB_USER
          valueFrom: 
            secretKeyRef:
              name: todo-app-back-secret
              key: MONGODB_USER
        - name: MONGODB_PARAMS
          valueFrom: 
            secretKeyRef:
              name: todo-app-back-secret
              key: MONGODB_PARAMS
        - name: MONGODB_PROTO
          valueFrom: 
            secretKeyRef:
              name: todo-app-back-secret
              key: MONGODB_PROTO
        - name: NODE_PORT
          valueFrom: 
            secretKeyRef:
              name: todo-app-back-secret
              key: NODE_PORT
