apiVersion: v1
kind: Service
metadata:
  name: todo-app-back
  namespace: unir
  labels:
    app: todo-app-back
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: todo-app-back