apiVersion: v1
kind: Service
metadata:
  name: todo-app-back
  namespace: unir
  labels:
    app: todo-app-back
spec:
  selector:
    app: todo-app-back
  ports:
    - protocol: TCP
      port: 80         # Puerto en el que el servicio estará disponible
      targetPort: 80   # Puerto del contenedor en el Deployment
      nodePort: 30007  # Puerto en los nodos del clúster
  type: NodePort
