apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name
  namespace: unir
spec:
  replicas: 2
  selector:
    matchLabels:
      name: todoui
  template:
    metadata:
      labels:
        name: todoui
    spec:
      containers:
        - name: deploment-container-name
          image: jm9704/todo-ui:v1.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80