apiVersion: v1
kind: Service
metadata:
  labels:
    name: todo-ui
  name: todo-ui-loadbalancer
  namespace: app-unir
spec:
  type: LoadBalancer
  ports:
  - name: todo-ui
    port: 80
    protocol: TCP
  selector:
    name: todo-ui