apiVersion: v1
kind: Service
metadata:
  labels:
    name: todo-ui
  name: service-todo-ui
  namespace: app-unir
spec:
  type: NodePort
  ports:
  - name: todo-ui
    port: 80
    protocol: TCP
  selector:
    name: todo-ui